import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[window]
padding = { x = 5, y = 5 }
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[terminal]
osc52 = "CopyPaste"

[[hints.enabled]]
regex = '(?-u:\b)\w[^\s]+(?-u:\b)'
action = "Paste"
binding = { key = "H", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
action = "Paste"
binding = { key = "(", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(~|\\.|[\\w\\-]*)/([\\w\\-]+/?)*"
action = "Paste"
binding = { key = "*", mods = "Control|Shift" }
