import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[window]
padding = { x = 5, y = 5 }
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 15

[terminal]
osc52 = "CopyPaste"

[[hints.enabled]]
regex = '(?-u:\b)\w[^\s]+(?-u:\b)'
# hyperlinks = true
action = "Paste"
binding = { key = ")", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
# hyperlinks = true
action = "Paste"
binding = { key = "(", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(~|\\.|[\\w\\-]*)/([\\w\\-]+/?)*"
# hyperlinks = true
action = "Paste"
binding = { key = "*", mods = "Control|Shift" }
