watch-files: true
# model: openrouter/google/gemini-2.0-flash-001
# model: openrouter/google/gemini-2.5-pro-exp-03-25
# model: openrouter/google/gemini-2.5-pro-preview-03-25
# model: openrouter/deepseek/deepseek-r1
model: openrouter/openai/gpt-4o-mini
# model: openrouter/anthropic/claude-3.7-sonnet
# model: openrouter/google/gemini-2.5-flash-preview
# model: openrouter/deepseek/deepseek-chat-v3-0324:free
dark-mode: true
