#!/usr/zsh

#### VARIABLES

export ZVM_VI_ESCAPE_BINDKEY=jk
export EDITOR=nvim
export VISUAL=nvim
export ZSH_PLUGIN_ROOT=$HOME/.local/share/zsh/plugins
export PATH=$HOME/bin:$PATH
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_DEFAULT_OPTS="--multi --bind ctrl-y:accept"
export PGDATA=$HOME/.local/share/postgres
AFTER_INIT_HAS_RUN=0

[[ -f $ZDOTDIR/envrc ]] && source $ZDOTDIR/envrc # Private environment variables can be loaded here.

##### COMMAND INIT

eval "$(starship init zsh)"
eval "$(mise activate zsh)"

# Run these commands after zsh-vim-mode init
zvm_after_init ()
{
	eval "$(fzf --zsh)"
	bindkey '^[[Z' reverse-menu-complete
	bindkey '^y' autosuggest-accept
}

##### COMPLETIONS

fpath=($ZSH_PLUGIN_ROOT/zsh-completions/src $fpath)
autoload -U compinit && compinit
zstyle ':completion:*' menu select

##### ALIASES

alias ls="lsd"
alias lsl="lsd -larth"
alias lg="lazygit"
alias cat="bat"
alias neovim="cd ~/.config/nvim"
alias dotfiles="cd $HOME/Dev/dotfiles"
alias dfpush="gh auth switch && git push && gh auth switch" # Simpler pushing/pull dotfiles from work
alias dfpull="gh auth switch && git pull && gh auth switch"
alias kgp="kubectl get pods"
alias ch="cd ~/Dev/pmpclear-webapp"
alias aware="cd ~/Dev/pmpaware-webapp"
alias kccc="kubectl config current-context"
alias jil='jira issue list -a "$(jira me)" -q "sprint = P1"'
alias zsource="source $ZDOTDIR/.zshrc"

##### FUNCTIONS

ap ()
{
	export AWS_PROFILE=$(aws configure list-profiles | sort | fzf)
}

ksc ()
{
	kubectl config use-context $(kubectl config get-contexts | awk '{print $1}' | fzf)
}

##### PLUGINS

load_plugin ()
{
	PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
	PLUGIN_DIR=$ZSH_PLUGIN_ROOT/$PLUGIN_NAME
	if [[ ! -d $PLUGIN_DIR ]]; then
		mkdir -p $PLUGIN_DIR
		git clone https://www.github.com/$1.git $PLUGIN_DIR
	fi
	source $PLUGIN_DIR/$PLUGIN_NAME.plugin.zsh
}

update_plugins ()
{
	for dir in $ZSH_PLUGIN_ROOT/*(N/); do
		echo "Updating $dir..."
		cd $dir && git pull
	done
	
	
}

load_plugin "zsh-users/zsh-completions"
load_plugin "jeffreytse/zsh-vi-mode"
load_plugin "zsh-users/zsh-autosuggestions"
load_plugin "zsh-users/zsh-syntax-highlighting"
